package io.sylphy.app.core.extension

import io.sylphy.app.data.local.db.entity.TrackEntity
import io.sylphy.app.data.local.db.entity.TrackFtsEntity
import io.sylphy.app.data.local.db.entity.AlbumEntity
import io.sylphy.app.data.local.db.entity.ArtistEntity
import io.sylphy.app.data.local.db.entity.PlaylistEntity
import io.sylphy.app.data.model.Album
import io.sylphy.app.data.model.Artist
import io.sylphy.app.data.model.Playlist
import io.sylphy.app.data.model.Track
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken

private val gson = Gson()
private val floatListType = object : TypeToken<List<Float>>() {}.type

fun TrackEntity.toTrack(): Track = Track(
    id            = id,
    contentUri    = contentUri,
    title         = title,
    artist        = artist,
    album         = album,
    albumArtist   = albumArtist,
    genre         = genre,
    year          = year,
    trackNumber   = trackNumber,
    discNumber    = discNumber,
    durationMs    = durationMs,
    fileSize      = fileSize,
    mimeType      = mimeType,
    sampleRate    = sampleRate,
    bitRate       = bitRate,
    artworkPath   = artworkPath,
    waveformData  = waveformJson?.let { gson.fromJson(it, floatListType) },
    playCount     = playCount,
    lastPlayedAt  = lastPlayedAt,
    addedAt       = addedAt,
    isAvailable   = isAvailable,
    isFavorite    = isFavorite,
)

fun Track.toEntity(): TrackEntity = TrackEntity(
    id            = id,
    contentUri    = contentUri,
    title         = title,
    artist        = artist,
    album         = album,
    albumArtist   = albumArtist,
    genre         = genre,
    year          = year,
    trackNumber   = trackNumber,
    discNumber    = discNumber,
    durationMs    = durationMs,
    fileSize      = fileSize,
    mimeType      = mimeType,
    sampleRate    = sampleRate,
    bitRate       = bitRate,
    artworkPath   = artworkPath,
    waveformJson  = waveformData?.let { gson.toJson(it) },
    playCount     = playCount,
    lastPlayedAt  = lastPlayedAt,
    addedAt       = addedAt,
    isAvailable   = isAvailable,
    isFavorite    = isFavorite,
)

fun TrackEntity.toFtsEntity(): TrackFtsEntity = TrackFtsEntity(
    trackId = id,
    title   = title,
    artist  = artist,
    album   = album,
    genre   = genre.orEmpty(),
)

fun AlbumEntity.toAlbum(tracks: List<Track> = emptyList()): Album = Album(
    id          = id,
    title       = title,
    artist      = artist,
    albumArtist = albumArtist,
    year        = year,
    genre       = genre,
    artworkPath = artworkPath,
    trackCount  = trackCount,
    durationMs  = durationMs,
    addedAt     = addedAt,
    tracks      = tracks,
)

fun ArtistEntity.toArtist(): Artist = Artist(
    id          = id,
    name        = name,
    artworkPath = artworkPath,
    albumCount  = albumCount,
    trackCount  = trackCount,
)

fun PlaylistEntity.toPlaylist(tracks: List<Track> = emptyList()): Playlist = Playlist(
    id              = id,
    name            = name,
    description     = description,
    artworkPath     = artworkPath,
    isAutoGenerated = isAutoGenerated,
    trackCount      = trackCount,
    durationMs      = durationMs,
    createdAt       = createdAt,
    updatedAt       = updatedAt,
    tracks          = tracks,
)
