package io.sylphy.app.data.model

data class Playlist(
    val id: String,
    val name: String,
    val description: String? = null,
    val artworkPath: String? = null,
    val isAutoGenerated: Boolean = false,
    val trackCount: Int = 0,
    val durationMs: Long = 0L,
    val createdAt: Long,
    val updatedAt: Long,
    val tracks: List<Track> = emptyList(),
)
